name: MobDrops
main: me.scill.mobdrops.MobDrops
version: 1.1
author: Scill
commands:
   mobdrops:
      description: Reloads the MobDrops plugin.
      usage: /<command>
permissions:
   mobdrops.reload:
      description: Reloads the MobDrops plugin.
      default: op