name: ${project.name}
main: ${main.class}
version: ${project.version}
author: Scill
commands:
   mobdrops:
      description: Reloads the MobDrops plugin.
      usage: /<command>
permissions:
   mobdrops.reload:
      description: Reloads the MobDrops plugin.
      default: op